### ISSUE TITLE
Latest code doesn't run...

### ISSUE THREAD

**Issue by Creteil** [amit9838/mousam#140]
```
bigbob@bigbob-t480s:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
bigbob@bigbob-t480s:~$ mousam 
Traceback (most recent call last):
  File "/usr/bin/mousam", line 49, in <module>
    sys.exit(main.main(VERSION))
  File "/usr/share/mousam/mousam/main.py", line 82, in main
    app = WeatherApplication()
  File "/usr/share/mousam/mousam/main.py", line 36, in __init__
    flags=Gio.ApplicationFlags.DEFAULT_FLAGS)
AttributeError: type object 'ApplicationFlags' has no attribute 'DEFAULT_FLAGS'
bigbob@bigbob-t480s:~$
```

Any idea ?

**Comment by amit9838** [comment]
is it stable version or edge version?
you are running this as snap right?

**Comment by Creteil** [comment]
This is latest code fetched with :

git clone https://github.com/amit9838/mousam.git

And then created a « debian » package from it...

**Comment by amit9838** [comment]
i think you'll have to update changelog file with latest release tag. and update the version info wherever required.
I don't work on debian so can't help much. 🙂

**Comment by Creteil** [comment]
I have no problem to build the package, it was done correctly :

```
bigbob@bigbob-t480s:~/tmp/Building$ dpkg -l mousam
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom            Version          Architecture Description
+++-==============-================-============-=================================
ii  mousam         1.3.1-2-g96217e0 all          Weather for Linux
bigbob@bigbob-t480s:~/tmp/Building$
```

The error is when running the program...

**Comment by amit9838** [comment]
can you try the latest build for debian, https://github.com/amit9838/mousam/discussions/68,
this may help

**Comment by Creteil** [comment]
It throw same error :

```
bigbob@bigbob-t480s:~/Téléchargements$ sudo dpkg -i mousam_1.2.0~ubuntu22.04.1_all.deb 
dpkg: avertissement: dégradation (« downgrade ») de mousam depuis 1.2.0-unstable+202405221338~ubuntu22.04.1 vers 1.2.0~ubuntu22.04.1
(Lecture de la base de données... 711055 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de mousam_1.2.0~ubuntu22.04.1_all.deb ...
Dépaquetage de mousam (1.2.0~ubuntu22.04.1) sur (1.2.0-unstable+202405221338~ubuntu22.04.1) ...
Paramétrage de mousam (1.2.0~ubuntu22.04.1) ...
Traitement des actions différées (« triggers ») pour gnome-menus (3.36.0-1ubuntu3) ...
Traitement des actions différées (« triggers ») pour bamfdaemon (0.5.6+22.04.20220217-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Traitement des actions différées (« triggers ») pour mailcap (3.70+nmu1ubuntu1) ...
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.26-1ubuntu3) ...
Traitement des actions différées (« triggers ») pour doc-base (0.11.1) ...
Traitement de 1 fichier de documentation modifié…
Erreur dans « /usr/share/doc-base/mousam.mousam » : ligne 20 : aucune section « Format » n'est valable.
Remarque : « install-docs --verbose --check nom_fichier » peut donner plus de précisions au sujet de l'erreur ci-dessus.
Traitement des actions différées (« triggers ») pour libglib2.0-0:amd64 (2.72.4-0ubuntu2.3) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.17-2) ...
bigbob@bigbob-t480s:~/Téléchargements$ mousam
Traceback (most recent call last):
  File "/usr/bin/mousam", line 49, in <module>
    sys.exit(main.main(VERSION))
  File "/usr/share/mousam/mousam/main.py", line 83, in main
    app = WeatherApplication()
  File "/usr/share/mousam/mousam/main.py", line 35, in __init__
    flags=Gio.ApplicationFlags.DEFAULT_FLAGS)
AttributeError: type object 'ApplicationFlags' has no attribute 'DEFAULT_FLAGS'
bigbob@bigbob-t480s:~/Téléchargements$
```

**Comment by hsbasu** [comment]
Gtk4 apps are notoriously difficult to start from terminal. Use the .desktop file to start the app.

**Comment by Creteil** [comment]
Your answer doesn't make sense, it doesn't start even when using the .desktop file...

**Comment by hsbasu** [comment]
How did you install it?

**Comment by Creteil** [comment]
Just read my message [#7](https://github.com/amit9838/mousam/issues/140#issuecomment-2175933377)... (I have downloaded and installed your package version...).

**Comment by Creteil** [comment]
By the way, can it working only under « wayland », because, on my side, I use « Ubuntu Unity 22.04 » under X11...

**Comment by hsbasu** [comment]
> By the way, can it working only under « wayland », because, on my side, I use « Ubuntu Unity 22.04 » under X11...

I also use X11 on cinnamon. So it should not be an issue.

**Comment by Creteil** [comment]
Just fetch the latest code today to give it another try, even the package is build successfully, same error occur when trying to launch the application :

```
bigbob@bigbob-t480s:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
^[[Abigbob@bigbob-t480s:~$ mousam 
Traceback (most recent call last):
  File "/usr/bin/mousam", line 49, in <module>
    sys.exit(main.main(VERSION))
  File "/usr/share/mousam/mousam/main.py", line 82, in main
    app = WeatherApplication()
  File "/usr/share/mousam/mousam/main.py", line 36, in __init__
    flags=Gio.ApplicationFlags.DEFAULT_FLAGS)
AttributeError: type object 'ApplicationFlags' has no attribute 'DEFAULT_FLAGS'
bigbob@bigbob-t480s:~$
```
